add very basic tests

diff --git a/mdcheckr b/mdcheckr
--- a/mdcheckr
+++ b/mdcheckr
@@ -1,9 +1,34 @@
 #!/bin/bash
 set -e
+# mdcheckr: practical CI testing for markdown files
+# Copyright (c) 2017 Michael Billington < michael.billingotn@gmail.com >
+#
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is
+# furnished to do so, subject to the following conditions:
+#
+# The above copyright notice and this permission notice shall be included in all
+# copies or substantial portions of the Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+# SOFTWARE.
 
-# Extract URLs from Markdown file via Pandoc
 function extract_links() {
-  pandoc -f markdown_github "$fn" | (xmllint --nowarning --html --xpath '*//a/@href' - 2> /dev/null || true) | sed 's/ href="\([^"]*\)"/\1\n/g'
+  # Extract URLs from Markdown file:
+  # - Render via Pandoc
+  # - Extract URI via href="" attribute
+  # - Format as one URI per line
+  pandoc -f markdown_github "$1" | \
+    (xmllint --nowarning --html --xpath '*//a/@href' - 2> /dev/null || true) | \
+    sed 's/ href="\([^"]*\)"/\1\n/g'
 }
 
 function green() {
@@ -26,7 +51,7 @@ for i in $@; do
   # Jump into same dir as file
   cd `dirname "$i"`
   echo "Checking $i .."
-  extract_links "$fn" | while read -r line; do
+  while read -r line; do
     # Notify of check
     echo -n "- $line ";
     fail=0
@@ -41,9 +66,20 @@ for i in $@; do
     if [ "$fail" == 1 ]; then
       red "FAIL"
       explain "$i" "$REASON"
+      failures=$((failures+1))
     else
       green "OK"
     fi
-  done;
+  done < <(extract_links "$fn")
 done
+
+# Return to initial directory
 cd $DIR
+
+# Log number of failures
+if [ "$failures" -gt 0 ]; then
+  echo "Done, with $failures warning(s)."
+fi
+
+# Use number of failures as exit code
+exit $failures
