help output

diff --git a/mdcheckr b/mdcheckr
--- a/mdcheckr
+++ b/mdcheckr
@@ -224,10 +224,17 @@ function explain() {
   >&2 echo -e Warning:$_file:$_line_no:$_message
 }
 
-# Parse command-line optins
-function show_help() {
+# Parse command-line optins...
+function show_usage() {
   cat << EOF
-usage: mdcheckr [ -h ] FILE ..
+usage: mdcheckr [ -h | --help | -v | --version ] FILE ..
+EOF
+}
+
+
+function show_help() {
+  show_usage
+  cat << EOF
 
 A testing tool to detect quality problems with your Markdown documentation.
 
@@ -248,8 +255,25 @@ function show_version() {
 VERSION="1.0"
 OPTIND=1
 VERBOSITY=3
-while getopts hv opt; do
+while getopts "hv-:" opt; do
   case $opt in
+    -)
+      case "${OPTARG}" in
+        help)
+          show_help
+          exit 0
+          ;;
+        version)
+          show_version
+          exit 0
+          ;;
+        *)
+          echo "$0: Illegal option -- ${OPTARG}" >&2
+          show_usage >&2
+          exit 1
+          ;;
+      esac
+      ;;
     h)
       show_help
       exit 0
@@ -259,12 +283,19 @@ while getopts hv opt; do
       exit 0
       ;;
     *)
-      show_help >&2
+      show_usage >&2
       exit 1
     ;;
   esac
 done
 shift "$((OPTIND-1))"
+
+# Require at least one filename to be specified
+if [ "$#" -lt 1 ]; then
+    echo "$0: Missing file operand" >&2
+    show_usage >&2
+fi
+
 
 # Explicitly check for each dependency
 for i in which pandoc xmllint curl; do which $i > /dev/null 2> /dev/null || (
